destination: ../docs/
title: SshTo.net documentation
email: info@sshto.net
description: Use standard and secure SSH to remotely access your IoT, Ubuntu, Mac, Router, Raspberry PI, Servers .. anything from anywhere in the world
baseurl: /realgrandrew/auth0-login-test/sshtonet-landing/docs/
url: https://www.sshto.net/docs
twitter_username: realga_v 
github_username: sshtonet 

sass:
  style: compressed

paginate: 12
paginate_path: "/:num/"

author_img_s: terminal_ico.png
author_img: terminal_ico.png

google_analytics: UA-87587271-1
disqus: sshtonet

navigation:
  - text: Home
    url: /
  - text: Categories
    url: /categories.html
  - text: Tags
    url: /tags.html

read_more: Read More
env: production
minify_html: false # Set to true only when it is production. Increase significant build time.

# Build settings
markdown: kramdown

sticky: sticky # Tag used for sticky post
sticky_count: 3 # Number of sticky post shown

gems:
  - jekyll-paginate
  - jekyll-feed
  
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
